AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - exe/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/omniauth-investec.rb
